stages:
  - build

dataflow-worker-image:
  stage: build
  tags:
    - brm-dev-data-processing-runner
  variables:
    IMAGE_NAME: "dataflow-worker"
  extends:
    - .common-dataflow-worker-image

etl-demo-launcher-image:
  stage: build
  tags:
    - brm-dev-data-processing-runner
  variables:
    PIPELINE_NAME: "${PIPELINE_NAME}"
    JOB_LAUNCHER_PATH: "pipelines/${PIPELINE_NAME}/job_launcher.py"
  extends:
    - .common-deploy-launcher-image

etl-demo-template:
  stage: build
  tags:
    - brm-dev-data-processing-runner
  variables:
    PIPELINE_NAME: "${PIPELINE_NAME}"
    LAUNCHER_TAG: ${CI_COMMIT_SHORT_SHA}
  extends:
    - .common-deploy-dataflow-template

etl-demo-configs:
  stage: build
  tags:
    - brm-dev-data-processing-runner
  variables:
    PIPELINE_NAME: "${PIPELINE_NAME}"
    LOCAL_CONFIGS_PATH: "devops/${PIPELINE_NAME}/configs/*"
  extends:
    - .common-deploy-configs-on-gcs