stages:
  - build

dataflow-worker-image:
  stage: build
  tags:
    - trd-dev-data-processing-runner
  variables:
    IMAGE_NAME: "dataflow-worker"
  extends:
    - .common-dataflow-worker-image

load-raw-launcher-image:
  stage: build
  tags:
    - trd-dev-data-processing-runner
  variables:
    PIPELINE_NAME: "load_raw"
    JOB_LAUNCHER_PATH: "pipelines/load_raw/job_launcher.py"
  extends:
    - .common-deploy-launcher-image

load-raw-template:
  stage: build
  tags:
    - trd-dev-data-processing-runner
  variables:
    PIPELINE_NAME: "load_raw"
    LAUNCHER_TAG: ${CI_COMMIT_SHORT_SHA}
  extends:
    - .common-deploy-dataflow-template

load-raw-configs:
  stage: build
  tags:
    - trd-dev-data-processing-runner
  variables:
    PIPELINE_NAME: "load_raw"
    LOCAL_CONFIGS_PATH: "devops/load_raw/configs"
  extends:
    - .common-deploy-configs-on-gcs

